import asyncio
import os
import secrets
from sqlite_engine import SQLiteLedgerEngine
from verifier import ForensicAuditVerifier

class EphemeralKeyProvider:
    def __init__(self):
        # In production, this would pull from a secure KMS environment
        self._secret_key = b'static_test_key_material_32_bytes'
    def get_key_material(self, key_id: str) -> bytes:
        return self._secret_key

async def automated_sentinel_loop():
    db_path = "blind_test_ledger.db"
    key_provider = EphemeralKeyProvider()
    
    print("[-] Automated Forensic Sentinel active. Press Ctrl+C to stop.")
    
    while True:
        if not os.path.exists(db_path):
            print("[?] Waiting for target database to be generated by the system...")
            await asyncio.sleep(5)
            continue
            
        # Initialize engine connection cleanly
        engine = SQLiteLedgerEngine(db_path, key_provider)
        try:
            await engine.initialize()
            verifier = ForensicAuditVerifier(engine)
            
            # Blindly execute validation pass
            report = await verifier.verify_complete_ledger_chain()
            
            if report['status'] == "VERIFIED":
                print(f"[✅ SYSTEM OK] Verified {report['manifests_processed']} blocks. Integrity nominal.")
            else:
                print(f"[🚨 CRITICAL ALARM] CRYPTOGRAPHIC CORRUPTION DETECTED!")
                print(f"    Total Violations: {len(report['errors'])}")
                for err in report['errors']:
                    print(f"    [-] ALERT DETAILS: {err}")
                    
        except Exception as e:
            print(f"[⚠️ WARNING] Sentinel connection glitch: {str(e)}")
        finally:
            await engine.close()
            
        # Wait 5 seconds before automatically scanning again
        await asyncio.sleep(5)

if __name__ == "__main__":
    try:
        asyncio.run(automated_sentinel_loop())
    except KeyboardInterrupt:
        print("\n[-] Sentinel loop stopped.")
